mariadb:
  enabled: false

wordpress:
  wordpressPassword: foo
  mariadb:
    enabled: false
  externalDatabase:
    host: localhost
    user: wp_user
    password: quantex@123
    database: testwp
    port: 3306
  service:
    type: LoadBalancer
