apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    chart: mongodb
    repoURL: https://github.com/bitnami/charts/tree/main/bitnami/mongodb
    targetRevision: HEAD
    helm:
      releaseName: mongodb
      # valueFiles:
      #   - test-mongodb.yaml
      #   - https://github.com/Hardeep4770/flask-nextjs-kubernetes.git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal