apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami/mongodb
    repoURL: https://github.com/bitnami/charts
    targetRevision: HEAD
    helm:
      releaseName: mongodb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: my-mongodb