apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts
    path: bitnami/mongodb
    targetRevision: HEAD
    helm:
      releaseName: mongodb
      valueFiles:
        - https://github.com/Hardeep4770/flask-nextjs-kubernetes/blob/main/test-mongodb-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: my-mongodb