apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mymongoexpress
  project: default
  source:
    chart: mongo-express
    repoURL: https://cowboysysop.github.io/charts/
    targetRevision: 2.7.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: mongoexpress
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   namespace: argocd
# spec:
#   project: default

#   source:
#     repoURL: https://github.com/Hardeep4770/flask-nextjs-kubernetes.git
#     targetRevision: HEAD
#     path: kubernetes/mongoexpress
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: myexpress

#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       selfHeal: true
#       prune: true
