prometheus-mysql-exporter:
  mysql:
    db: testwp
    host: mysql.default.svc.cluster.local
    user: wp_user
    pass: quantex@123
  env:
    - name: DATA_SOURCE_NAME
      value: "wp_user:quantex@123@(mysql.default.svc.cluster.local:3306)/testwp"

  #     prometheus-mysql-exporter:
  # mysqldExporter:
  #   enabled: true
  #   extraEnv:
  #     - name: DATA_SOURCE_NAME
  #       value: "wp_user:quantex@123@(mysql.default.svc.cluster.local:3306)/testwp"
