apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mymongo
  project: default
  source:
    chart: mongodb
    helm:
      values: |
        architecture: replicaset
        replicaCount: 3
        persistence:
          storageClass: "standard"
          size: 512Mi
        auth:
          rootPassword: secret-root-pwd
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: 13.4.4
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
