apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Hardeep4770/flask-nextjs-kubernetes.git
    targetRevision: HEAD
    path: helm-mysql-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
