prometheus:
  server:
    ingress:
      ## If true, Prometheus server Ingress will be created
      ##
      enabled: true

      ## Prometheus server Ingress hostnames
      ## Must be provided if Ingress is enabled
      ##
      hosts:
        - prometheus.wordpress.local
    prometheus.yml:
      scrape_configs:
        - job_name: "mysql"
          static_configs:
            - targets: ["localhost:9104"]
