grafana:
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClassName: "standard"
  grafana.ini:
    server:
      domain: monitoring.wordpress.local
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts:
      - "monitoring.wordpress.local"
    path: "/grafana"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: MySQL
          type: mysql
          url: localhost:3306
          database: testwp
          access: proxy
          isDefault: true
          basicAuth: true
          basicAuthUser: wp_user
          basicAuthPassword: quantex@123