grafana:
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClassName: "standard"
  grafana.ini:
    server:
      domain: monitoring.wordpress.local
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts:
      - "monitoring.wordpress.local"
    path: "/grafana"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: MySQL
          type: mysql
          url: mysql.default.svc.cluster.local:3306
          database: testwp
          access: proxy
          user: wp_user
          jsonData:
            maxOpenConns: 0 # Grafana v5.4+
            maxIdleConns: 2 # Grafana v5.4+
            connMaxLifetime: 14400 # Grafana v5.4+
          secureJsonData:
            password: quantex@123
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.default.svc.cluster.local
          access: proxy
          isDefault: true
        - name: elasticsearch-v7-filebeat
          type: elasticsearch
          access: proxy
          database: '[filebeat-]YYYY.MM.DD'
          url: http://localhost:9200
          jsonData:
            interval: Daily
            timeField: '@timestamp'
            esVersion: '7.0.0'
            logMessageField: message
            logLevelField: fields.level
            dataLinks:
              - datasourceUid: my_jaeger_uid # Target UID needs to be known
                field: traceID
                url: '$${__value.raw}' # Careful about the double "$$" because of env var expansion