grafana:
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClassName: "standard"
  grafana.ini:
    server:
      domain: monitoring.wordpress.local
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts:
      - "monitoring.wordpress.local"
    path: "/grafana"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: MySQL
          type: mysql
          url: mysql.default.svc.cluster.local:3306
          database: testwp
          access: proxy
          user: wp_user
          password: quantex@123
          jsonData:
            maxOpenConns: 0 # Grafana v5.4+
            maxIdleConns: 2 # Grafana v5.4+
            connMaxLifetime: 14400 # Grafana v5.4+