grafana:
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClassName: "standard"
  grafana.ini:
    server:
      domain: monitoring.wordpress.local
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts:
      - "monitoring.wordpress.local"
    path: "/grafana"